DashEditor.py -e DAT/ARM00L.BIN
DashEditor.py -e DAT/ARM00R.BIN
DashEditor.py -e DAT/ARM01R.BIN
DashEditor.py -e DAT/ARM02R.BIN
DashEditor.py -e DAT/ARM03R.BIN
DashEditor.py -e DAT/ARM04L.BIN
DashEditor.py -e DAT/ARM04R.BIN
DashEditor.py -e DAT/ARM05R.BIN
DashEditor.py -e DAT/ARM06R.BIN
DashEditor.py -e DAT/ARM07R.BIN
DashEditor.py -e DAT/ARM08R.BIN
DashEditor.py -e DAT/ARM09R.BIN
DashEditor.py -e DAT/ARM10R.BIN
DashEditor.py -e DAT/ARM11R.BIN
DashEditor.py -e DAT/ARM12R.BIN
DashEditor.py -e DAT/ARM13R.BIN
DashEditor.py -e DAT/BS16VAB1.BIN
DashEditor.py -e DAT/DEMO_DAT.BIN
DashEditor.py -e DAT/EXIT_MAP.BIN
DashEditor.py -e DAT/EXIT_SUB.BIN
DashEditor.py -e DAT/EXIT_SUP.BIN
DashEditor.py -e DAT/FONT.BIN
DashEditor.py -e DAT/GAMEOVER.BIN
DashEditor.py -e DAT/GAUGE.BIN
DashEditor.py -e DAT/HEAD00.BIN
DashEditor.py -e DAT/HEAD01.BIN
DashEditor.py -e DAT/INIT_DAT.BIN
DashEditor.py -e DAT/KAIFONT.BIN
DashEditor.py -e DAT/LEG00.BIN
DashEditor.py -e DAT/LEG01.BIN
DashEditor.py -e DAT/MAP_A1.BIN
DashEditor.py -e DAT/MAP_A2.BIN
DashEditor.py -e DAT/MAP_B1.BIN
DashEditor.py -e DAT/MAP_B2.BIN
DashEditor.py -e DAT/MAP_B3.BIN
DashEditor.py -e DAT/ST00.BIN
DashEditor.py -e DAT/ST00_00.BIN
DashEditor.py -e DAT/ST00_01.BIN
DashEditor.py -e DAT/ST00_02.BIN
DashEditor.py -e DAT/ST00_03.BIN
DashEditor.py -e DAT/ST00_04.BIN
DashEditor.py -e DAT/ST01.BIN
DashEditor.py -e DAT/ST02.BIN
DashEditor.py -e DAT/ST02_00.BIN
DashEditor.py -e DAT/ST02_01.BIN
DashEditor.py -e DAT/ST02_02.BIN
DashEditor.py -e DAT/ST03.BIN
DashEditor.py -e DAT/ST03B.BIN
DashEditor.py -e DAT/ST03_00.BIN
DashEditor.py -e DAT/ST03_00B.BIN
DashEditor.py -e DAT/ST03_00C.BIN
DashEditor.py -e DAT/ST03_00D.BIN
DashEditor.py -e DAT/ST03_03.BIN
DashEditor.py -e DAT/ST03_05.BIN
DashEditor.py -e DAT/ST03_06.BIN
DashEditor.py -e DAT/ST03_07.BIN
DashEditor.py -e DAT/ST03_08.BIN
DashEditor.py -e DAT/ST04.BIN
DashEditor.py -e DAT/ST04B.BIN
DashEditor.py -e DAT/ST04_00.BIN
DashEditor.py -e DAT/ST04_00B.BIN
DashEditor.py -e DAT/ST04_00C.BIN
DashEditor.py -e DAT/ST04_00D.BIN
DashEditor.py -e DAT/ST04_00E.BIN
DashEditor.py -e DAT/ST04_00F.BIN
DashEditor.py -e DAT/ST04_01.BIN
DashEditor.py -e DAT/ST04_02.BIN
DashEditor.py -e DAT/ST04_03.BIN
DashEditor.py -e DAT/ST04_04.BIN
DashEditor.py -e DAT/ST04_05.BIN
DashEditor.py -e DAT/ST05.BIN
DashEditor.py -e DAT/ST05_00.BIN
DashEditor.py -e DAT/ST05_00B.BIN
DashEditor.py -e DAT/ST05_00C.BIN
DashEditor.py -e DAT/ST05_00D.BIN
DashEditor.py -e DAT/ST05_00E.BIN
DashEditor.py -e DAT/ST05_00F.BIN
DashEditor.py -e DAT/ST05_00G.BIN
DashEditor.py -e DAT/ST05_00H.BIN
DashEditor.py -e DAT/ST05_00I.BIN
DashEditor.py -e DAT/ST05_00J.BIN
DashEditor.py -e DAT/ST05_01.BIN
DashEditor.py -e DAT/ST05_01C.BIN
DashEditor.py -e DAT/ST05_02.BIN
DashEditor.py -e DAT/ST05_04.BIN
DashEditor.py -e DAT/ST06.BIN
DashEditor.py -e DAT/ST06_00.BIN
DashEditor.py -e DAT/ST06_00B.BIN
DashEditor.py -e DAT/ST06_00C.BIN
DashEditor.py -e DAT/ST06_00D.BIN
DashEditor.py -e DAT/ST06_01.BIN
DashEditor.py -e DAT/ST06_01B.BIN
DashEditor.py -e DAT/ST06_02.BIN
DashEditor.py -e DAT/ST06_02C.BIN
DashEditor.py -e DAT/ST06_02D.BIN
DashEditor.py -e DAT/ST06_03.BIN
DashEditor.py -e DAT/ST06_04.BIN
DashEditor.py -e DAT/ST07.BIN
DashEditor.py -e DAT/ST07_00.BIN
DashEditor.py -e DAT/ST07_05.BIN
DashEditor.py -e DAT/ST07_05B.BIN
DashEditor.py -e DAT/ST08.BIN
DashEditor.py -e DAT/ST08_00.BIN
DashEditor.py -e DAT/ST08_00B.BIN
DashEditor.py -e DAT/ST08_00C.BIN
DashEditor.py -e DAT/ST08_01.BIN
DashEditor.py -e DAT/ST08_02.BIN
DashEditor.py -e DAT/ST08_03.BIN
DashEditor.py -e DAT/ST08_04.BIN
DashEditor.py -e DAT/ST09.BIN
DashEditor.py -e DAT/ST09_00.BIN
DashEditor.py -e DAT/ST09_02.BIN
DashEditor.py -e DAT/ST09_03.BIN
DashEditor.py -e DAT/ST09_05.BIN
DashEditor.py -e DAT/ST0A.BIN
DashEditor.py -e DAT/ST0A_00.BIN
DashEditor.py -e DAT/ST0A_00C.BIN
DashEditor.py -e DAT/ST0A_00D.BIN
DashEditor.py -e DAT/ST0B.BIN
DashEditor.py -e DAT/ST0B_00.BIN
DashEditor.py -e DAT/ST0B_00B.BIN
DashEditor.py -e DAT/ST0B_00C.BIN
DashEditor.py -e DAT/ST0B_00D.BIN
DashEditor.py -e DAT/ST0B_00E.BIN
DashEditor.py -e DAT/ST0B_01.BIN
DashEditor.py -e DAT/ST0B_01B.BIN
DashEditor.py -e DAT/ST0C.BIN
DashEditor.py -e DAT/ST0CB.BIN
DashEditor.py -e DAT/ST0CC.BIN
DashEditor.py -e DAT/ST0D.BIN
DashEditor.py -e DAT/ST0D_00.BIN
DashEditor.py -e DAT/ST0D_00C.BIN
DashEditor.py -e DAT/ST0D_00D.BIN
DashEditor.py -e DAT/ST0D_01.BIN
DashEditor.py -e DAT/ST0D_02.BIN
DashEditor.py -e DAT/ST0D_03.BIN
DashEditor.py -e DAT/ST0E.BIN
DashEditor.py -e DAT/ST0F.BIN
DashEditor.py -e DAT/ST0F_00.BIN
DashEditor.py -e DAT/ST0F_02.BIN
DashEditor.py -e DAT/ST0F_02B.BIN
DashEditor.py -e DAT/ST0F_02C.BIN
DashEditor.py -e DAT/ST0F_02D.BIN
DashEditor.py -e DAT/ST0F_03.BIN
DashEditor.py -e DAT/ST10.BIN
DashEditor.py -e DAT/ST10B.BIN
DashEditor.py -e DAT/ST10_00.BIN
DashEditor.py -e DAT/ST10_00B.BIN
DashEditor.py -e DAT/ST10_00C.BIN
DashEditor.py -e DAT/ST10_01.BIN
DashEditor.py -e DAT/ST10_02.BIN
DashEditor.py -e DAT/ST10_03.BIN
DashEditor.py -e DAT/ST10_04.BIN
DashEditor.py -e DAT/ST10_05.BIN
DashEditor.py -e DAT/ST11.BIN
DashEditor.py -e DAT/ST11B.BIN
DashEditor.py -e DAT/ST11_00.BIN
DashEditor.py -e DAT/ST11_00B.BIN
DashEditor.py -e DAT/ST11_00C.BIN
DashEditor.py -e DAT/ST12.BIN
DashEditor.py -e DAT/ST12_00.BIN
DashEditor.py -e DAT/ST13.BIN
DashEditor.py -e DAT/ST13_00.BIN
DashEditor.py -e DAT/ST13_00B.BIN
DashEditor.py -e DAT/ST14.BIN
DashEditor.py -e DAT/ST14_00.BIN
DashEditor.py -e DAT/ST14_00B.BIN
DashEditor.py -e DAT/ST15.BIN
DashEditor.py -e DAT/ST15_00.BIN
DashEditor.py -e DAT/ST16.BIN
DashEditor.py -e DAT/ST16_00.BIN
DashEditor.py -e DAT/ST16_00B.BIN
DashEditor.py -e DAT/ST17.BIN
DashEditor.py -e DAT/ST17B.BIN
DashEditor.py -e DAT/ST17C.BIN
DashEditor.py -e DAT/ST18.BIN
DashEditor.py -e DAT/ST18_00.BIN
DashEditor.py -e DAT/ST19.BIN
DashEditor.py -e DAT/ST19B.BIN
DashEditor.py -e DAT/ST19C.BIN
DashEditor.py -e DAT/ST19_00.BIN
DashEditor.py -e DAT/ST19_03.BIN
DashEditor.py -e DAT/ST1A.BIN
DashEditor.py -e DAT/ST1A_00.BIN
DashEditor.py -e DAT/ST1A_01.BIN
DashEditor.py -e DAT/ST1A_01B.BIN
DashEditor.py -e DAT/ST1A_01C.BIN
DashEditor.py -e DAT/ST1A_02.BIN
DashEditor.py -e DAT/ST1A_02B.BIN
DashEditor.py -e DAT/ST1A_02C.BIN
DashEditor.py -e DAT/ST1A_02D.BIN
DashEditor.py -e DAT/ST1B.BIN
DashEditor.py -e DAT/ST1B_00.BIN
DashEditor.py -e DAT/ST1B_00B.BIN
DashEditor.py -e DAT/ST1C.BIN
DashEditor.py -e DAT/ST1D.BIN
DashEditor.py -e DAT/ST1D_00.BIN
DashEditor.py -e DAT/ST1D_01.BIN
DashEditor.py -e DAT/ST1D_02.BIN
DashEditor.py -e DAT/ST1E.BIN
DashEditor.py -e DAT/ST1E_06.BIN
DashEditor.py -e DAT/SUB_KEY.BIN
DashEditor.py -e DAT/SUB_WPN.BIN
DashEditor.py -e DAT/SUPPORT.BIN
DashEditor.py -e DAT/SUPPORT2.BIN